"""uploaded_by

Revision ID: 30ce6f29fc31
Revises: 1424d1823e45
Create Date: 2024-10-27 15:39:00.404543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ce6f29fc31'
down_revision: Union[str, None] = '1424d1823e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uploaded_by', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'uploaded_by')
    # ### end Alembic commands ###
