"""Changed model name

Revision ID: 7834ca76f7c4
Revises: 7b7ec95cab09
Create Date: 2024-10-27 15:11:46.683387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7834ca76f7c4'
down_revision: Union[str, None] = '7b7ec95cab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
